#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
pkill polybar &
sh /home/liam/.config/polybar/launch.sh &
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/startup.sh
pkill picom
feh --bg-fill /home/liam/Pictures/maybewallpaper.jpg & 
picom --experimental-backends &
bspc monitor -d I II III IV V VI VII VIII IX X
killall "dunst"
dunst &
killall "flameshot"
flameshot &

bspc config border_width         4 
bspc config window_gap           15
# bspc config top_padding          26

# Border
#TODO: If possible, look into scripting an if/else statement that disables this depending on A the type of window open, and B, if it's the only window open
#      Example:
#      Say I have only one window open in workspace A, I would want it to by default turn off, unless:
#           the window is a console/terminal emulator
#           or the window is floating
#           otherwise, have the border be much more minimal
#I could possibly use bspc subscribe + awk scripts (wtf is an awk script)
# Attempt?

bspc config focused_border_color        "#7373ff" 
# bspc config focused_border_color        "#ff3465" 
# bspc config focused_border_color        "#ffffff" 
# bspc config focused_border_color        "#504945"
bspc config normal_border_color         "#1e0f2c"
bspc config active_border_color         "#fb4934"
# bspc config active_border_color         "#230B52"
bspc config presel_feedback_color		"#4c566a"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config pointer_action2 resize_corner

# Rules
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a discord desktop='^5' focus=on follow=on



#TODO It would be nice to be able to configure an eww widget that can popup with a pretty looking list of all my sxhkd keybinds,it would make things especially helpful if I ever ended up sharing my dots
#TODO properly learn chezmoi!!!!
#
#
#
#Scratchpad configuration (credit to the arch wiki)

